var APP = require("core");

// Ti.App.Properties.setBool('APP:USER:autoGenerated', false)
// Ti.App.Properties.setBool('APP:USER:hasLoggedIn', false)

var USER = {
	init: function(callback) {
		APP.log("debug", "USER.init");

		if(Ti.App.Properties.getBool('APP:USER:isSaved')) {
			USER.login(Ti.App.Properties.getString('APP:USER:login'), Ti.App.Properties.getString('APP:USER:password'), callback);
		} else {
			USER.autoCreate(callback);
		}
	},
	save: function(id, login, password) {
		APP.log("debug", "USER.save @success");

		Ti.App.Properties.setString('APP:USER:id', id);
		Ti.App.Properties.setString('APP:USER:login', login);
		Ti.App.Properties.setString('APP:USER:password', password);

		Ti.App.Properties.setBool('APP:USER:isSaved', true);
		Ti.App.Properties.setBool('APP:USER:isLoggedIn', true);
	},
	create: function(_params) {
		var options = {
			password: _params.password,
			password_confirmation: _params.password_confirmation
		};

		if(_params.email) {
			options.email = _params.email;
		}
		if(_params.username) {
			options.username = _params.username;
		}
		if(_params.first_name) {
			options.first_name = _params.first_name;
		}
		if(_params.last_name) {
			options.last_name = _params.last_name;
		}

		APP.Cloud.Users.create(options, function(e) {
			if(e.success) {
				APP.log("debug", "USER.create @success");
				APP.log("trace", JSON.stringify(user));

				var user = e.users[0];
				USER.save(user.id, (_params.username) ? _params.username : _params.email, _params.password);

				if(_params.success) {
					_params.success(user);
				}
			} else {
				APP.log("debug", "USER.create @error");
				APP.log("trace", JSON.stringify(e));
			}
		});
	},
	autoCreate: function(success) {
		var password = Ti.Platform.id.toString(36).slice(-16);

		USER.create({
			username: Ti.Platform.id,
			password: password,
			password_confirmation: password,
			success: function(user) {
				APP.log("debug", "USER.autoCreate @success");
				APP.log("trace", JSON.stringify(user));

				if(success) {
					success();
				}
			}
		});

	},
	login: function(login, password, success) {
		APP.Cloud.Users.login({
			login: login,
			password: password
		}, function(e) {
			if(e.success) {

				var user = e.users[0];
				USER.save(user.id, (_params.username) ? _params.username : _params.email, _params.password);

				APP.log("debug", "USER.login @success");
				APP.log("trace", JSON.stringify(user));

				if(success) {
					success();
				}
			} else {
				APP.log("debug", "USER.login @error");
				APP.log("trace", JSON.stringify(e));
			}
		});
	},
	logout: function() {

	}
};

module.exports = USER;