#!/bin/bash

APPLICATION="$1"
NAME="$2"

mv /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data_chariti

cd /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti

mv /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data_$APPLICATION /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data

./CBUILD -a "$APPLICATION" -n "$NAME" -i "com.mcongrove.chariti.$APPLICATION" -d false -w "/Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti"

mv /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data_$APPLICATION

mv /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data_chariti /Users/matthewcongrove/Documents/Titanium_Studio_Workspace/Chariti/app/lib/data